---
build_requires:
  ExtUtils::MakeMaker: 6.42
  Pod::Coverage::TrustPod: 0
  Test::More: 0
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.08
  Test::UseAllModules: 0
  aliased: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DataFlow
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  HTML::TreeBuilder::XPath: 0
  LWP::Curl: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  MooseX::OneArgNew: 0
  MooseX::Types::IO: 0
  Queue::Base: 0
  Scalar::Util: 0
  WWW::Mechanize: 0
  namespace::autoclean: 0
  version: 0.86
resources:
  license: http://dev.perl.org/licenses/
version: 0.090000
