---
abstract: 'A component for dataflow processing'
author:
  - 'Alexei Znamensky <russoz@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.94
  Test::UseAllModules: 0
  aliased: 0
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DataFlow
requires:
  Carp: 0
  Data::Dumper: 0
  DateTime: 0
  Encode: 0
  HTML::TreeBuilder::XPath: 0
  LWP::Curl: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 1.01
  MooseX::OneArgNew: 0
  MooseX::Traits: 0
  MooseX::Types::IO: 0
  Queue::Base: 2.1
  SQL::Abstract: 0
  Scalar::Util: 0
  Text::CSV: 0
  WWW::Mechanize: 0
  autodie: 0
  perl: 5.008
resources:
  bugtracker: http://github.com/russoz/DataFlow/issues
  repository: git://github.com/russoz/DataFlow.git
version: 1.110860
